import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/context/authProvider'
import { ThemeProvider } from '@/context/themeProvider'
const inter = Inter({ subsets: ['latin'] })
import { Navbar } from '@/components/Nav'
import { SideNav, SideNavMobile } from '@/components/SideNav'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <Navbar />
            <SideNav />
            <SideNavMobile>
              <SideNav isMobileView />
            </SideNavMobile>
            {children}
          </AuthProvider>

        </ThemeProvider>
      </body>
    </html>
  )
}
